
services:
  bot:
    build:
      context: .
      dockerfile: DockerfileBot
      args:
        - --no-cache
    container_name: bot_stats
    volumes:
      - ./bot:/app
      - ./logs/:/app/logs
#    restart: unless-stopped
    env_file:
      - ./bot/.env

